fname = input("Enter First Name: ")
lname = input("Enter Last Name: ")
mname = input("Enter Middle Name: ")
bday = input("Enter Birth Date (mm/dd/yyyy): ")
gender = input("Enter Gender(Male/Female): ")
address = input("Enter Address: ")
course = input("Enter Course: ")
yLevel = input("Enter Year Level: ")

print("====================================================")
print("First Name:\t",fname)
print("Last Name:\t",lname)
print("Middle Name:\t",mname)
print("Birth Date:\t",bday)
print("Gender:\t\t",gender)
print("Address:\t",address)
print("Course:\t\t",course)
print("Year Level:\t",yLevel)